In [69]:
## LINEAR REGRESSION

In [70]:
import torch
import numpy as np

In [71]:
# trying to model apple and orange yeilds from temperature, rainfall and humidity factors
# apples = w11*temp + w12*rainfall + w13*humidity + b1
# oranges = w21*temp + w22*rainfall + w23*humidity + b2
# inputs (temp, rainfall, humidity)(obervations x each variable-temp,rain.humidity)
# targets (apples, oranges) (outputs per observation x outputs-apples,oranges)
inputs = torch.tensor([[73, 67, 43],
                       [91, 88, 64],
                       [87, 134, 58],
                       [102, 43, 37],
                       [69, 96, 70]], dtype = torch.float32)

targets = torch.tensor([[56, 70],
                        [81, 101],
                        [119, 133],
                        [22, 37],
                        [103, 119]], dtype = torch.float32)


In [72]:
# display inputs and targets
print(inputs)
print(targets)
print(inputs.size())
print(targets.size())

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
torch.Size([5, 3])
torch.Size([5, 2])


In [73]:
# random initialization of weights and biases
# we are interested in how yeild changes w.r.t weights and bisases so grad is required for w and b
w = torch.randn(2, 3, requires_grad = True) #(no of outputs x no of variables)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[ 0.6733,  1.0448, -1.0625],
        [-0.6036, -0.6970, -2.2284]], requires_grad=True)
tensor([-0.6762,  1.7396], requires_grad=True)


In [74]:
# defining the model
def model(x):
    return x @ w.t() + b

In [75]:
# generate predictions
preds = model(inputs)
print(preds, preds.size())

tensor([[  72.7840, -184.8402],
        [  84.5304, -257.1379],
        [ 136.2710, -273.4130],
        [  73.6098, -172.2461],
        [  71.7014, -262.8057]], grad_fn=<AddBackward0>) torch.Size([5, 2])


In [76]:
# As we started with random weights and biases, the predictions are not perfect
# Loss function- using mean sqaure error- avg of sq of differences
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    # numel calculates the number of elements
    return torch.sum(diff * diff) / diff.numel()



In [77]:
# training the model. 
# set the number of interations for training-updating weights so that loss is minumum
# in each interation the following happens
# send inputs to model
# predictions are given
# loss is calculated compared to target yeilds
# gradients w.r.t to w and b are calculated
# if gradients are positive, w, b values need to be reduced to reduce loss
# if gradients are negative, w, b values need to be incremented to reduce loss
# w and b values are updated accordingly
# w, b gradients are reset to zero before another iteration as pytorch accumulates gradients
# finally ater training print predictions and loss

for i in range(100):
    # making yeild predictions
    preds = model(inputs)
    # computing loss
    loss = mse(preds, targets)
    # computing gradients
    loss.backward ()
        # updating weights
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        #pytorch accumulates gradients so make them zero before another iteration
        w.grad.zero_()
        b.grad.zero_()
print(loss)
print(preds)
print(targets)

tensor(484.3190, grad_fn=<DivBackward0>)
tensor([[ 61.8627,  76.4614],
        [ 73.1147,  89.7703],
        [131.8174, 147.8629],
        [ 47.8083,  69.5492],
        [ 70.3725,  81.5364]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
