In [43]:
import torch

In [3]:
help(torch.randn_like)

Help on built-in function randn_like:

randn_like(...)
    randn_like(input, dtype=None, layout=None, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor with the same size as :attr:`input` that is filled with
    random numbers from a normal distribution with mean 0 and variance 1.
    ``torch.randn_like(input)`` is equivalent to
    ``torch.randn(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.
    
    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
            Default: if ``None``, defaults to the layout of :attr:`input`.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None

In [12]:
#constructs a (3,5) empty tensor with garbage values
x = torch.empty(3, 5)
print(x)

tensor([[ 0.0000e+00, -1.5846e+29,  0.0000e+00, -1.5846e+29,  5.6052e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  3.0854e-14, -3.6902e+19,  3.1322e-14]])


In [15]:
# constructs randomly initialized matrix of size (3,5)
x = torch.rand(3,5)
print (x)

tensor([[0.8161, 0.7455, 0.5429, 0.2420, 0.8490],
        [0.6665, 0.0304, 0.5690, 0.1335, 0.2071],
        [0.2339, 0.1517, 0.8671, 0.2576, 0.7253]])


In [18]:
#constructs a matrix filled with 0s with specified datatype
x = torch.zeros(3, 5, dtype = torch.double)
print (x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [22]:
#contructs a tensor similar to an existing tensor
x = x.new_ones(3, 5, dtype = torch.double)
print (x)

x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])


In [24]:
#use.size() to determine the size of a tensor
print(x.size())

torch.Size([3, 5])


In [32]:
#different syntaxes for adding

#1
y = torch.zeros(3,5)
print(x+y)

#2
print(torch.add(x, y))

#3 specifying an output tensor
result = torch.empty(3,5)
torch.add(x, y, out = result)
print(result)

#4 using y itself as the output tensor; will modify y
#operations use _ when changing in place
y.add_(x)
print(y)

#experiment
y = torch.sub(y, x)
torch.add(x, y, out = y)
print(y)

tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])
tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])
tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])
tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])
tensor([[ 0.6728, -0.4301, -0.6048, -0.4645, -0.5008],
        [-0.8935, -0.1885, -0.2643,  0.7556,  1.0974],
        [-0.8662, -1.3941, -0.9596,  0.3617,  0.4326]])


In [33]:
#numpy like indexing
x = torch.randn(4, 4)
y = x.view(16) # number of columns
z = x.view(-1,2) #1-1 infers the dimension to match the original number of elements. -1,2 will give 8x2;-1,4 will give 4x4.
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

In [35]:
#to get the value of a single element tensor as a python numnber use .item()
x = torch.randn(1) #creating a single element tensor with a random number
print(x)
print(x.item())

tensor([1.0283])
1.0282673835754395


In [37]:
#Converting torch tensor to numpy array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [40]:
a.add_(1)
print(a)
print(b)
#both a and b change values even though operation is performed only on a

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [46]:
#converting numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 2, out = a)
#a and b are both modified even though operation is performed only on a
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
